/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AccessRights": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Api": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "Assets": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "Entries": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Hrf": {
      "type": "sst.aws.Router"
      "url": string
    }
    "Journals": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Plays": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Users": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}

import "sst"
export {}