/// <reference path="./.sst/platform/config.d.ts" />

// The client (haunt-roll-fail/index.html) is templated server-side at request
// time (see GoodGame.scala). We read the real file here, at synth time, and
// emit it as a TS module so api.ts can import it as a plain string -- this
// avoids needing to ship a separate non-JS asset alongside the Lambda bundle.
//
// sst.config.ts disallows top-level imports, so `fs` is imported dynamically.
async function generateTemplate() {
  const { readFileSync, writeFileSync } = await import("node:fs");
  let html = readFileSync("../haunt-roll-fail/index.html", "utf8");

  // The mirrored assets (serverless/assets/, pulled from the live site) have
  // omen/background as .webp, not the .png this repo's index.html still
  // references -- production apparently moved off .png at some point.
  html = html.replace('url("omen.png")', 'url("omen.webp")');
  html = html.replace('url("background.png")', 'url("background.webp")');

  writeFileSync(
    "src/template.generated.ts",
    `// Generated by sst.config.ts from ../haunt-roll-fail/index.html. Do not edit.\nexport const indexHtml = ${JSON.stringify(html)};\n`,
  );
}

export default $config({
  app(input) {
    return {
      name: "hrf",
      removal: input?.stage === "production" ? "retain" : "remove",
      home: "aws",
    };
  },
  async run() {
    await generateTemplate();

    const users = new sst.aws.Dynamo("Users", {
      fields: { id: "string" },
      primaryIndex: { hashKey: "id" },
    });

    const journals = new sst.aws.Dynamo("Journals", {
      fields: { id: "string" },
      primaryIndex: { hashKey: "id" },
    });

    const entries = new sst.aws.Dynamo("Entries", {
      fields: { journalId: "string", index: "number" },
      primaryIndex: { hashKey: "journalId", rangeKey: "index" },
    });

    const accessRights = new sst.aws.Dynamo("AccessRights", {
      fields: { journalId: "string", userId: "string" },
      primaryIndex: { hashKey: "journalId", rangeKey: "userId" },
    });

    const plays = new sst.aws.Dynamo("Plays", {
      fields: { secret: "string" },
      primaryIndex: { hashKey: "secret" },
    });

    const router = new sst.aws.Router("Hrf");

    // The card/board art, fonts, etc. that live under /hrf/* are not part of
    // this git repo (see README.md). Drop them into serverless/assets/ before
    // deploying -- scripts/build-client.sh picks them up automatically.
    const assets = new sst.aws.StaticSite("Assets", {
      path: ".",
      build: {
        command: "./scripts/build-client.sh",
        output: "dist",
      },
      router: { instance: router, path: "/hrf" },
    });

    const api = new sst.aws.Function("Api", {
      handler: "src/api.handler",
      link: [users, journals, entries, accessRights, plays],
      url: { router: { instance: router, path: "/" } },
      environment: {
        // Populated after the Router's CloudFront domain is known; used to
        // build the data-server/data-meta/<base href> values the client needs,
        // mirroring the <url>/<cdn> CLI args GoodGame.scala used to take.
        SITE_URL: router.url,
      },
    });

    return {
      url: router.url,
      api: api.url,
      assets: assets.url,
    };
  },
});
